name: 新闻过滤和翻译

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'  # 每天上海时间01:00（UTC 17:00），在排序之后30分钟

jobs:
  filter-translate-news:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: 设置 Git
        run: |
          git config user.name "NowScott"
          git config user.email "nowscott@qq.com"

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 安装 Chrome 和 ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y

      - name: 安装 Python 依赖
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager chromedriver-autoinstaller deep-translator

      - name: 创建config.ini si no existe
        run: |
          if [ ! -f config.ini ]; then
            echo "Creando config.ini vacío..."
            touch config.ini
          fi

      - name: 运行 main.py (过滤、排序和翻译)
        run: |
          python src/main.py

      - name: 提交更改
        run: |
          git add news_archive/es/
          echo "添加翻译文件后的 Git 状态:"
          git status
          git diff --cached --exit-code news_archive/es/ || (
            DATE=$(TZ="Asia/Shanghai" date "+%Y-%m-%d %H:%M:%S")
            echo "正在提交翻译新闻更改..."
            git commit -m "新闻翻译更新于 $DATE"
            git push origin main
            echo '翻译更新成功'
          )